/* DOM 元素引用 */
(function (App) {
  "use strict";

  const { $ } = App.Utils;

  App.Dom = {
    fileInput: $('fileInput'),
    exportBtn: $('exportBtn'),
    checkAll: $('checkAll'),
    selInfo: $('selInfo'),
    gallery: $('gallery'),
    emptySide: $('emptySide'),
    currentName: $('currentName'),
    addTextBtn: $('addTextBtn'),
    exportOneBtn: $('exportOneBtn'),
    fontUploadBtn: $('fontUploadBtn'),
    fontInput: $('fontInput'),
    canvasArea: $('canvasArea'),
    stage: $('stage'),
    stageImg: $('stageImg'),
    emptyEditor: $('emptyEditor'),
    dropzone: $('dropzone'),
    boxToolbar: $('boxToolbar'),
    textProps: $('textProps'),
    drawProps: $('drawProps'),
    propsPanel: $('propsPanel'),
    propsHint: $('propsHint'),
    propsHintText: $('propsHintText'),
    tbColor: $('tbColor'),
    tbColorBtn: $('tbColorBtn'),
    tbColorEyedropper: $('tbColorEyedropper'),
    tbStrokeColor: $('tbStrokeColor'),
    tbStrokeColorBtn: $('tbStrokeColorBtn'),
    tbStrokeColorEyedropper: $('tbStrokeColorEyedropper'),
    tbSizeMinus: $('tbSizeMinus'),
    tbSize: $('tbSize'),
    tbSizePlus: $('tbSizePlus'),
    tbFont: $('tbFont'),
    tbBold: $('tbBold'),
    tbVert: $('tbVert'),
    tbRotateStart: $('tbRotateStart'),
    tbRotateExit: $('tbRotateExit'),
    tbRotateHint: $('tbRotateHint'),
    tbRotMinus: $('tbRotMinus'),
    tbRot: $('tbRot'),
    tbRotPlus: $('tbRotPlus'),
    tbStroke: $('tbStroke'),
    tbStrokeW: $('tbStrokeW'),
    tbStrokeVal: $('tbStrokeVal'),
    tbDelBtn: $('tbDelBtn'),
    toastEl: $('toast'),
    mirror: $('mirror'),
    clearAllBtn: $('clearAllBtn'),
    clearCacheBtn: $('clearCacheBtn'),
    editor: $('editor'),
    modeTextBtn: $('modeTextBtn'),
    modeDrawBtn: $('modeDrawBtn'),
    drawToolbar: $('drawToolbar'),
    drawRaster: $('drawRaster'),
    drawShapeLayer: $('drawShapeLayer'),
    drawColor: $('drawColor'),
    drawColorBtn: $('drawColorBtn'),
    drawBrushSize: $('drawBrushSize'),
    drawEraserSize: $('drawEraserSize'),
    drawUndoBtn: $('drawUndoBtn'),
    drawRedoBtn: $('drawRedoBtn'),
    drawDelBtn: $('drawDelBtn'),
    galleryPanel: $('galleryPanel'),
    brandOwlBtn: $('brandOwlBtn'),
    owlThemeAudio: $('owlThemeAudio'),
    themeToggleBtn: $('themeToggleBtn'),
    helpBtn: $('helpBtn'),
    helpModal: $('helpModal'),
    helpModalClose: $('helpModalClose'),
    helpModalOk: $('helpModalOk'),
    sidebarCollapseGallery: $('sidebarCollapseGallery'),
    sidebarCollapseProps: $('sidebarCollapseProps')
  };
})(window.App = window.App || {});
